name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Get the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Copy the project to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "~/myapp"

      # 3️⃣ SSH into EC2 and set up Python environment
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/myapp
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            # If you have a systemd service:
            if sudo systemctl is-active --quiet myapp; then
              sudo systemctl restart myapp
            else
              echo "No systemd service found. You can run your app manually for now."
            fi
